### ISSUE TITLE
Создать прототипы элементов рельефа

### ISSUE THREAD

**Issue by Melakonde** [DENEDI22/PlanetsExploration#12]
скалы, кратеры, пропасти, плато и т.п.

**Comment by Melakonde** [comment]
М.А.:Сделал 4 меша скал. В планах еще хотя бы десяток таких модулей сделать.

**Comment by MakarenkoAndy** [comment]
![Rocks3](https://user-images.githubusercontent.com/61984932/81721732-0267aa00-9489-11ea-8742-edad1f8710d5.png)
![untitled](https://user-images.githubusercontent.com/61984932/81721748-072c5e00-9489-11ea-9559-5d42db12a2e9.png)

**Comment by MakarenkoAndy** [comment]
![Unbenannt](https://user-images.githubusercontent.com/61984932/81721965-5d999c80-9489-11ea-8469-d814492464bd.jpg)

**Comment by MakarenkoAndy** [comment]
Сделал 12 различных объектов элементов рельефа: 3 вида гор, плато, мостик, кратер (в нем есть вход в пещеру, но саму пещеру еще надо делать. ) и т.п.

**Comment by MakarenkoAndy** [comment]
![Overview](https://user-images.githubusercontent.com/61984932/82757844-9e7ba480-9deb-11ea-80e4-c93d23b46542.png)
![Bridge6](https://user-images.githubusercontent.com/61984932/82757850-a9363980-9deb-11ea-939a-771f13e61929.png)
![Overview2](https://user-images.githubusercontent.com/61984932/82757857-b3f0ce80-9deb-11ea-83f3-027ba239a993.png)
![Overview6](https://user-images.githubusercontent.com/61984932/82757864-bf43fa00-9deb-11ea-9a3d-4dd18456915a.png)
